[package]
name = "nd_chess"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["n-vec"]

[dependencies]
bevy = "0.16"
bevy_granite = {path = "Y:/dependencies/bevy_granite"}
bevy_flycam = "*"
# n-vec = {path = "n-vec"}

[profile.dev.package."*"]
opt-level = 3